import Head from "next/head";
import { GetStaticProps } from "next";
import SuggestionFeedback from "../components/SuggestionFeedback";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Menu from "../components/Menu";
import TabletMenu from "../components/TabletMenu";
import { url, FeedbackData, menuVariants } from "../lib/Constant";

export default function Home({ feedback }: { feedback: FeedbackData }) {
  const productRequests: any[] = feedback["productRequests"];
  const [openMenu, setOpenMenu] = useState<boolean>(false);
  const [filter, setFilter] = useState<string>("");

  return (
    <main className='grid items-start overflow-x-hidden relative min-h-screen lg:px-24 d:px-36 d:py-20 bg-rice-white'>
      <Head>
        <title>Product Feedback</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <section className='grid d:grid-cols-4 d:items-start'>
        <article className='grid t:grid-cols-3 d:grid-cols-1 d:p-0 t:p-12 t:gap-3 d:gap-6 bg-rice-white'>
          <header className='grid grid-cols-2 t:grid-cols-1 items-center t:items-end d:h-40 d:px-8 py-4 px-6 t:rounded-lg text-white bg-no-repeat bg-center bg-cover bg-m-header t:bg-t-header d:bg-d-header'>
            <article className='grid'>
              <h3 className='font-semibold t:font-bold t:text-lg text-left'>
                Fullstack Project
              </h3>
              <h5 className='text-xs t:text-sm text-white text-opacity-70 font-medium'>
                Feedback Board
              </h5>
            </article>
            <motion.button
              whileHover={{ scale: 1.1 }}
              className='justify-self-end t:hidden'
              onClick={() => setOpenMenu(!openMenu)}
            >
              <motion.svg
                width='20'
                height='17'
                stroke='white'
                xmlns='http://www.w3.org/2000/svg'
              >
                <g fill='#FFF' fillRule='evenodd'>
                  <motion.path d='M0 0h20v3H0zM0 7h20v3H0zM0 14h20v3H0z' />
                </g>
              </motion.svg>
            </motion.button>
          </header>
          <TabletMenu
            productRequests={productRequests}
            filter={filter}
            onFilter={setFilter}
          />
        </article>
        <AnimatePresence initial={false}>
          <motion.article
            variants={menuVariants}
            initial={{ opacity: 0 }}
            animate={openMenu ? "visible" : "hidden"}
            exit='hidden'
            className='z-10 t:hidden absolute inset-0 top-[4.5rem] bg-gray-600 bg-opacity-50'
          >
            <Menu
              productRequests={productRequests}
              filter={filter}
              onFilter={setFilter}
              onOpenMenu={() => setOpenMenu(!openMenu)}
            />
          </motion.article>
        </AnimatePresence>
        <SuggestionFeedback productRequests={productRequests} filter={filter} />
      </section>
    </main>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`${url}/api`, {
    method: "GET",
  });
  const feedback = await res.json();

  return {
    props: {
      feedback,
    },
  };
};
